---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prod
  namespace: prod
  labels:
    app: prod
    tier: frontend
    version: v1
data:
  client.url: localhost:80
  mongo.db.url: mongodb://todo-mongo-service:27017/todo-app
  port: "3000"
  
---
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: prod
  namespace: prod
  labels:
    app: prod
    tier: frontend
    version: v1
data:
  JWT_SECRET: dGhpc0lzTXlTZWNyZXRLZXlGb3JKV1QqQC5bMTIz
---

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod
  namespace: prod
spec:
  selector:
    matchLabels:
      app: prod
      tier: frontend
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: prod
        tier: frontend
        name: prod
        version: v1
    spec:
      containers:
        - name: prod
          image: 'us-central1-docker.pkg.dev/western-mix-343614/prod/app:b99c1f8574b2b6278261def9c039458fc6317b6e'
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
          envFrom:
          - secretRef:
              name: prod

          env:
            - name: CLIENT
              valueFrom:
                configMapKeyRef:
                  name: prod
                  key: client.url
            - name: MONGODB_URL
              valueFrom:
                configMapKeyRef:
                  name: prod
                  key: mongo.db.url
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: prod
                  key: port
                  
          
---
---
apiVersion: v1
kind: Service
metadata:
  name: prod
  namespace: prod
  labels:
    app: prod
    tier: frontend
    version: v1
spec:
  selector:
    app: prod
    tier: frontend
    version: v1
  ports:
  - port: 3000
    targetPort: 3000
  type: LoadBalancer
---